### ISSUE TITLE
some module required 

### ISSUE THREAD

**Issue by backtoback1** [maxwellkoh/2FAssassin#5]
Hi i tried to use this script but i face many problems 
when start the assassin.py it's show me this error 

cat: /root/.msf4/loot/ssh_login.txt: No such file or directory

`cat: /root/.msf4/loot/ssh_login.txt: No such file or directory
Traceback (most recent call last):
  File "assassin.py", line 13, in <module>
    from cert.analysis import detest
  File "/root/Desktop/tools/2FAssassin/cert/analysis/detest.py", line 8, in <module>
    from classes.Colour import Colour
  File "/root/Desktop/tools/2FAssassin/classes/__init__.py", line 2, in <module>
    import Spider
ImportError: No module named Spider
`

can you explain how to install and which modules required 

Thanks

**Comment by maxwellkoh** [comment]
1) sudo touch /root/.msf4/loot/ssh_login.txt
2) comment out Spider module, I had removed that module -----> # import Spider
