### ISSUE TITLE
Several problems

### ISSUE THREAD

**Issue by eudomoniacc** [maxwellkoh/2FAssassin#6]
cat: /root/.msf4/loot/ssh_login.txt: Böyle bir dosya ya da dizin yok (There is no such file)
Traceback (most recent call last):
  File "assassin.py", line 13, in <module>
    from cert.analysis import detest
  File "/root/2FAssassin/cert/analysis/detest.py", line 8, in <module>
    from classes.Colour import Colour
  File "/root/2FAssassin/classes/__init__.py", line 2, in <module>
    import Spider
ImportError: No module named Spider

Operating system : Kali 2017.3

**Comment by maxwellkoh** [comment]
https://github.com/maxwellkoh/2FAssassin/issues/4
